# Generated by Django 5.1.4 on 2024-12-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agnim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_img', models.ImageField(upload_to='SkillImage/')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='career',
            field=models.CharField(max_length=50),
        ),
    ]
