# Generated by Django 5.1.4 on 2024-12-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agnim', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
